version: "3"

services:
  frontend:
    build: ../frontend
    command: ["yarn", "start"]
    volumes:
      - ../frontend:/frontend
    ports:
      - "3000:3000"
    stdin_open: true

  backend:
    build: ../backend
    command: ["yarn", "start"]
    volumes:
      - ../backend:/backend
    links:
      - frontend
    ports:
      - "4000:4000"
    stdin_open: true
